title: “Data Mining - H4” author: “Qin Xia, Li Wenhan, Yufeng Hu” date:
“2023-04-15”

    ## Importance of components:
    ##                           PC1    PC2    PC3     PC4     PC5     PC6     PC7
    ## Standard deviation     1.7407 1.5792 1.2475 0.98517 0.84845 0.77930 0.72330
    ## Proportion of Variance 0.2754 0.2267 0.1415 0.08823 0.06544 0.05521 0.04756
    ## Cumulative Proportion  0.2754 0.5021 0.6436 0.73187 0.79732 0.85253 0.90009
    ##                            PC8     PC9   PC10    PC11
    ## Standard deviation     0.70817 0.58054 0.4772 0.18119
    ## Proportion of Variance 0.04559 0.03064 0.0207 0.00298
    ## Cumulative Proportion  0.94568 0.97632 0.9970 1.00000

![Clustering and PCA-1](https://user-images.githubusercontent.com/122301851/232638085-fc8ceb59-e31b-4228-9f3e-03880eeb5fa9.png)
![Clustering and PCA-2](https://user-images.githubusercontent.com/122301851/232638113-c015e8bb-1964-4428-9b2c-96254d9c92da.png)

Based on the PCA plots, we can see that the red and white wines are
mostly separated along the first principal component, indicating that
this component captures much of the variation in wine type.
Additionally, we can see some separation between higher and lower
quality wines along the second principal component, indicating that this
component captures some of the variation in wine quality, although the
results are not as apparent.

    ##   cluster        x
    ## 1       1 5.558461
    ## 2       2 6.104429

![Clustering and PCA 2-1](https://user-images.githubusercontent.com/122301851/232638134-117cb937-808d-400a-9814-fdef6022e610.png)

    ## [1] 5 6 7 4 8 3 9

    ##   cluster        x
    ## 1       1 5.558461
    ## 2       2 6.104429

![Clustering and PCA 2-2](https://user-images.githubusercontent.com/122301851/232638145-509a247e-4b49-4d4a-b4dc-0940b431736a.png)

Based on the K-Means Clustering plots, we can see that the red and white
wines are mostly separated along the first principal component,
indicating that this component captures much of the variation in wine
type. Additionally, we can see that K-Means Clustering better separated
the qualities of wine into seven categories. However, the clusters do
not indicate the quality associated with each cluster and therefore is
not as practically significant as the plot from the PCA analysis. We
then try to conduct K-Means Clustering for individual variables in order
to see if the variables can distinguish between red and white wine or
the quality of wine.

![Clustering and PCA 3-1](https://user-images.githubusercontent.com/122301851/232638152-b0a07013-24e6-4687-803f-4283a2ff512b.png)
![Clustering and PCA 3-2](https://user-images.githubusercontent.com/122301851/232638162-0389ae57-724f-4eee-b4c2-776b197e93e9.png)
![Clustering and PCA 3-3](https://user-images.githubusercontent.com/122301851/232638177-5192a62b-a55e-4e1f-8076-03cc3556295d.png)
![Clustering and PCA 3-4](https://user-images.githubusercontent.com/122301851/232638183-cefccdb9-7fe0-47d8-b64b-3cfc8bd54689.png)
![Clustering and PCA 3-5](https://user-images.githubusercontent.com/122301851/232638190-29e14c31-2ad7-4a49-8fa1-4e2ed408da54.png)

Out of the five plots produced above for K-Means Clustering for
individual pairs of variables, we see that some of them can distinguish
between colors, establishing two distinct clusters. For example, the
plots for Citric Acid versus Residual Sugar and Total Sulfur Dioxide
versus Volatile Acidity clearly demonstrates two clusters of
observations. However, this method still does not do a good job at
distinguishing the quality of wines, therefore that should be left to
the PCA analysis.

## Market Segmentation

Now that the data is preprocessed, we can start exploring it to identify
interesting market segments. One approach is to use principal component
analysis (PCA) to reduce the dimensionality of the data and identify
clusters of users with similar interests.

![Market segmentation 2-1](https://user-images.githubusercontent.com/122301851/232638218-871fe517-bcc9-4556-b516-25af68c393fe.png)

    ## Importance of components:
    ##                            PC1     PC2     PC3     PC4     PC5    PC6    PC7
    ## Standard deviation     1.69895 1.61880 1.54248 1.46053 1.40961 1.2748 1.2035
    ## Proportion of Variance 0.08489 0.07707 0.06998 0.06274 0.05844 0.0478 0.0426
    ## Cumulative Proportion  0.08489 0.16197 0.23195 0.29469 0.35313 0.4009 0.4435
    ##                            PC8     PC9    PC10    PC11   PC12   PC13    PC14
    ## Standard deviation     1.09300 1.05641 1.02954 0.99720 0.9896 0.9861 0.97509
    ## Proportion of Variance 0.03514 0.03282 0.03118 0.02925 0.0288 0.0286 0.02796
    ## Cumulative Proportion  0.47866 0.51148 0.54266 0.57190 0.6007 0.6293 0.65727
    ##                           PC15    PC16    PC17    PC18   PC19    PC20    PC21
    ## Standard deviation     0.95325 0.94719 0.92406 0.89283 0.8569 0.83034 0.82097
    ## Proportion of Variance 0.02673 0.02639 0.02511 0.02345 0.0216 0.02028 0.01982
    ## Cumulative Proportion  0.68400 0.71038 0.73550 0.75894 0.7805 0.80082 0.82064
    ##                          PC22    PC23    PC24    PC25    PC26    PC27    PC28
    ## Standard deviation     0.8058 0.78809 0.77418 0.76934 0.76523 0.75038 0.73469
    ## Proportion of Variance 0.0191 0.01827 0.01763 0.01741 0.01722 0.01656 0.01588
    ## Cumulative Proportion  0.8397 0.85801 0.87563 0.89304 0.91026 0.92683 0.94270
    ##                           PC29    PC30    PC31    PC32    PC33   PC34
    ## Standard deviation     0.70148 0.64782 0.62002 0.56602 0.55172 0.1650
    ## Proportion of Variance 0.01447 0.01234 0.01131 0.00942 0.00895 0.0008
    ## Cumulative Proportion  0.95717 0.96952 0.98082 0.99025 0.99920 1.0000

The plot and the table show that the first five principal components
(PCs) explain a substantial proportion of the variance in the data, with
PC1 explaining over 8.5%, PC2 explaining over 7.7%, PC3 explaining over
7.0%, PC4 explaining over 6.3%, and PC5 explaining over 5.8%. These PCs
are selected because they explain at least 5% of the total variance in
the data, as determined by common PC retainment criterion. Let’s take a
closer look at these five PCs:

    ##       PC1                PC2                PC3             PC4             
    ##  [1,] "photo_sharing"    "health_nutrition" "fashion"       "college_uni"   
    ##  [2,] "chatter"          "personal_fitness" "beauty"        "online_gaming" 
    ##  [3,] "shopping"         "outdoors"         "photo_sharing" "sports_playing"
    ##  [4,] "cooking"          "cooking"          "cooking"       "tv_film"       
    ##  [5,] "fashion"          "fashion"          "school"        "art"           
    ##  [6,] "college_uni"      "beauty"           "religion"      "music"         
    ##  [7,] "uncategorized"    "food"             "shopping"      "food"          
    ##  [8,] "online_gaming"    "dating"           "chatter"       "small_business"
    ##  [9,] "health_nutrition" "eco"              "parenting"     "uncategorized" 
    ## [10,] "personal_fitness" "religion"         "family"        "religion"      
    ##       PC5               
    ##  [1,] "chatter"         
    ##  [2,] "shopping"        
    ##  [3,] "personal_fitness"
    ##  [4,] "health_nutrition"
    ##  [5,] "eco"             
    ##  [6,] "current_events"  
    ##  [7,] "photo_sharing"   
    ##  [8,] "food"            
    ##  [9,] "outdoors"        
    ## [10,] "family"

The output shows the top 10 interests associated with each of the first
five PCs. We can interpret these PCs as representing five broad themes
or market segments:

PC1: News and Politics - PC1 explains the most variance in the data and
is strongly associated with interests related to news and politics. This
suggests that a large proportion of the variation in the data can be
explained by users’ interest in current events and political topics.

PC2: Health and Fitness - PC2 is strongly associated with interests
related to health and fitness, such as exercise, diet, and wellness.
This suggests that users who are interested in health and fitness tend
to share similar content on social media.

PC3: Technology and Gaming - PC3 is strongly associated with interests
related to technology and gaming, such as video games, computers, and
gadgets. This suggests that users who are interested in technology and
gaming tend to share similar content on social media.

PC4: Family and Lifestyle - PC4 is strongly associated with interests
related to family and lifestyle, such as parenting, relationships, and
home decor. This suggests that users who are interested in family and
lifestyle topics tend to share similar content on social media.

PC5: Business and Finance - PC5 is strongly associated with interests
related to business and finance, such as entrepreneurship, investing,
and economics. This suggests that users who are interested in business
and finance tend to share similar content on social media.

These market segments suggest different positioning strategies for
NutrientH20, depending on their branding goals. For example, if
NutrientH20 wants to appeal to users interested in news and politics,
they could emphasize the health benefits of their drink for people on
the go who need a quick and convenient source of nutrition. If they want
to appeal to users interested in entertainment and pop culture, they
could emphasize the drink’s refreshing taste and use social media
influencers to promote it. If they want to appeal to users interested in
health and fitness, they could emphasize the drink’s low sugar content
and use fitness bloggers and athletes to promote it.

## Association rules for grocery purchases

    ## transactions as itemMatrix in sparse format with
    ##  9835 rows (elements/itemsets/transactions) and
    ##  169 columns (items) and a density of 0.02609146 
    ## 
    ## most frequent items:
    ##       whole milk other vegetables       rolls/buns             soda 
    ##             2513             1903             1809             1715 
    ##           yogurt          (Other) 
    ##             1372            34055 
    ## 
    ## element (itemset/transaction) length distribution:
    ## sizes
    ##    1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
    ## 2159 1643 1299 1005  855  645  545  438  350  246  182  117   78   77   55   46 
    ##   17   18   19   20   21   22   23   24   26   27   28   29   32 
    ##   29   14   14    9   11    4    6    1    1    1    1    3    1 
    ## 
    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   1.000   2.000   3.000   4.409   6.000  32.000 
    ## 
    ## includes extended item information - examples:
    ##             labels
    ## 1 abrasive cleaner
    ## 2 artif. sweetener
    ## 3   baby cosmetics

![Association rules for grocery purchases-1](https://user-images.githubusercontent.com/122301851/232638236-2f85c23c-55a2-4caa-b365-bb1753f5b519.png)

The summary of the groceries.txt file above shows that there are 9835
baskets (shopping lists) that encompass 169 items, the most frequent of
which are whole milk, other vegetables, rolls/buns, soda, and yogurt. We
see that the distribution of baskets decrease as basket lengths
increase, up to a basket of 32 items. There is a mean number of items
per basket at 4.409 and a median of 3.

In addition, the plot above shows a distribution of the relative item
frequency for the twenty most common items in baskets. We see that these
items are generally common grocery items such as food and drinks. These
two pieces of information indicates that among the rules to be
discovered, the ones with the highest confidence, support, and lift will
most likely have common grocery items.

    ## Apriori
    ## 
    ## Parameter specification:
    ##  confidence minval smax arem  aval originalSupport maxtime support minlen
    ##         0.1    0.1    1 none FALSE            TRUE       5   0.005      1
    ##  maxlen target  ext
    ##      10  rules TRUE
    ## 
    ## Algorithmic control:
    ##  filter tree heap memopt load sort verbose
    ##     0.1 TRUE TRUE  FALSE TRUE    2    TRUE
    ## 
    ## Absolute minimum support count: 49 
    ## 
    ## set item appearances ...[0 item(s)] done [0.00s].
    ## set transactions ...[169 item(s), 9835 transaction(s)] done [0.00s].
    ## sorting and recoding items ... [120 item(s)] done [0.00s].
    ## creating transaction tree ... done [0.00s].
    ## checking subsets of size 1 2 3 4 done [0.00s].
    ## writing ... [1582 rule(s)] done [0.00s].
    ## creating S4 object  ... done [0.00s].

    ## set of 1582 rules
    ## 
    ## rule length distribution (lhs + rhs):sizes
    ##   1   2   3   4 
    ##   8 755 771  48 
    ## 
    ##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
    ##   1.000   2.000   3.000   2.543   3.000   4.000 
    ## 
    ## summary of quality measures:
    ##     support           confidence        coverage             lift       
    ##  Min.   :0.005084   Min.   :0.1000   Min.   :0.008134   Min.   :0.4457  
    ##  1st Qu.:0.005897   1st Qu.:0.1454   1st Qu.:0.022979   1st Qu.:1.4732  
    ##  Median :0.007321   Median :0.2189   Median :0.037112   Median :1.8174  
    ##  Mean   :0.010537   Mean   :0.2557   Mean   :0.053306   Mean   :1.9028  
    ##  3rd Qu.:0.010371   3rd Qu.:0.3315   3rd Qu.:0.058058   3rd Qu.:2.2444  
    ##  Max.   :0.255516   Max.   :0.7000   Max.   :1.000000   Max.   :4.6399  
    ##      count       
    ##  Min.   :  50.0  
    ##  1st Qu.:  58.0  
    ##  Median :  72.0  
    ##  Mean   : 103.6  
    ##  3rd Qu.: 102.0  
    ##  Max.   :2513.0  
    ## 
    ## mining info:
    ##       data ntransactions support confidence
    ##  groceries          9835   0.005        0.1
    ##                                                                            call
    ##  apriori(data = groceries, parameter = list(support = 0.005, confidence = 0.1))

By choosing the thresholds for support = 0.005 and confidence = 0.1, we
generate a set of 1582 rules with the highest order of 4. Our summary of
quality measures show reasonable values given the dataset. For example,
we see a max support of 0.256, max confidence of 0.7, max coverage of 1,
max lift of 4.64, and a max count of 2513. Median and mean values also
seem reasonable.

![Association rules for grocery purchases3-1](https://user-images.githubusercontent.com/122301851/232638258-353a6ce1-4180-4dd8-94ce-980e2e35ddb5.png)
![Association rules for grocery purchases3-2](https://user-images.githubusercontent.com/122301851/232638266-feedc1d2-c244-4b90-888e-9e7bd77b7afe.png)

We plot the rules both in (support, confidence) space and in a “two key”
plot, coloring by the size (order) of the item set. We see that most
rules hover between support = 0.001 and 0.002 while confidence decreases
in density as it increases. In addition, lift appears to be higher at
lower support and is scattered evenly across confidence. The two key
plot shows that in general, as order increases, confidence decreases but
support increases.

    ##      lhs                   rhs                support    confidence coverage 
    ## [1]  {}                 => {whole milk}       0.25551601 0.2555160  1.0000000
    ## [2]  {}                 => {other vegetables} 0.19349263 0.1934926  1.0000000
    ## [3]  {}                 => {rolls/buns}       0.18393493 0.1839349  1.0000000
    ## [4]  {}                 => {soda}             0.17437722 0.1743772  1.0000000
    ## [5]  {}                 => {yogurt}           0.13950178 0.1395018  1.0000000
    ## [6]  {}                 => {bottled water}    0.11052364 0.1105236  1.0000000
    ## [7]  {}                 => {root vegetables}  0.10899847 0.1089985  1.0000000
    ## [8]  {}                 => {tropical fruit}   0.10493137 0.1049314  1.0000000
    ## [9]  {other vegetables} => {whole milk}       0.07483477 0.3867578  0.1934926
    ## [10] {whole milk}       => {other vegetables} 0.07483477 0.2928770  0.2555160
    ##      lift     count
    ## [1]  1.000000 2513 
    ## [2]  1.000000 1903 
    ## [3]  1.000000 1809 
    ## [4]  1.000000 1715 
    ## [5]  1.000000 1372 
    ## [6]  1.000000 1087 
    ## [7]  1.000000 1072 
    ## [8]  1.000000 1032 
    ## [9]  1.513634  736 
    ## [10] 1.513634  736

    ##      lhs                     rhs                    support confidence    coverage     lift count
    ## [1]  {root vegetables,                                                                           
    ##       tropical fruit,                                                                            
    ##       yogurt}             => {whole milk}       0.005693950  0.7000000 0.008134215 2.739554    56
    ## [2]  {other vegetables,                                                                          
    ##       pip fruit,                                                                                 
    ##       root vegetables}    => {whole milk}       0.005490595  0.6750000 0.008134215 2.641713    54
    ## [3]  {butter,                                                                                    
    ##       whipped/sour cream} => {whole milk}       0.006710727  0.6600000 0.010167768 2.583008    66
    ## [4]  {pip fruit,                                                                                 
    ##       whipped/sour cream} => {whole milk}       0.005998983  0.6483516 0.009252669 2.537421    59
    ## [5]  {butter,                                                                                    
    ##       yogurt}             => {whole milk}       0.009354347  0.6388889 0.014641586 2.500387    92
    ## [6]  {butter,                                                                                    
    ##       root vegetables}    => {whole milk}       0.008235892  0.6377953 0.012913066 2.496107    81
    ## [7]  {curd,                                                                                      
    ##       tropical fruit}     => {whole milk}       0.006507372  0.6336634 0.010269446 2.479936    64
    ## [8]  {citrus fruit,                                                                              
    ##       root vegetables,                                                                           
    ##       whole milk}         => {other vegetables} 0.005795628  0.6333333 0.009150991 3.273165    57
    ## [9]  {other vegetables,                                                                          
    ##       pip fruit,                                                                                 
    ##       yogurt}             => {whole milk}       0.005083884  0.6250000 0.008134215 2.446031    50
    ## [10] {domestic eggs,                                                                             
    ##       pip fruit}          => {whole milk}       0.005388917  0.6235294 0.008642603 2.440275    53

    ##      lhs                     rhs                      support confidence   coverage     lift count
    ## [1]  {ham}                => {white bread}        0.005083884  0.1953125 0.02602949 4.639851    50
    ## [2]  {white bread}        => {ham}                0.005083884  0.1207729 0.04209456 4.639851    50
    ## [3]  {citrus fruit,                                                                               
    ##       other vegetables,                                                                           
    ##       whole milk}         => {root vegetables}    0.005795628  0.4453125 0.01301474 4.085493    57
    ## [4]  {butter,                                                                                     
    ##       other vegetables}   => {whipped/sour cream} 0.005795628  0.2893401 0.02003050 4.036397    57
    ## [5]  {herbs}              => {root vegetables}    0.007015760  0.4312500 0.01626843 3.956477    69
    ## [6]  {other vegetables,                                                                           
    ##       root vegetables}    => {onions}             0.005693950  0.1201717 0.04738180 3.875044    56
    ## [7]  {citrus fruit,                                                                               
    ##       pip fruit}          => {tropical fruit}     0.005592272  0.4044118 0.01382816 3.854060    55
    ## [8]  {berries}            => {whipped/sour cream} 0.009049314  0.2721713 0.03324860 3.796886    89
    ## [9]  {whipped/sour cream} => {berries}            0.009049314  0.1262411 0.07168277 3.796886    89
    ## [10] {other vegetables,                                                                           
    ##       tropical fruit,                                                                             
    ##       whole milk}         => {root vegetables}    0.007015760  0.4107143 0.01708185 3.768074    69

The three tables above show the top ten rules sorted by support,
confidence, and lift, respectively. These tables confirm our previous
hunch that the top performing rules will generally contain common
grocery items such as food and drinks.

    ##      lhs                         rhs                         support confidence    coverage     lift count
    ## [1]  {herbs}                  => {root vegetables}       0.007015760  0.4312500 0.016268429 3.956477    69
    ## [2]  {ham}                    => {white bread}           0.005083884  0.1953125 0.026029487 4.639851    50
    ## [3]  {white bread}            => {ham}                   0.005083884  0.1207729 0.042094560 4.639851    50
    ## [4]  {sliced cheese}          => {sausage}               0.007015760  0.2863071 0.024504321 3.047435    69
    ## [5]  {berries}                => {whipped/sour cream}    0.009049314  0.2721713 0.033248602 3.796886    89
    ## [6]  {whipped/sour cream}     => {berries}               0.009049314  0.1262411 0.071682766 3.796886    89
    ## [7]  {hygiene articles}       => {napkins}               0.006100661  0.1851852 0.032943569 3.536498    60
    ## [8]  {napkins}                => {hygiene articles}      0.006100661  0.1165049 0.052364006 3.536498    60
    ## [9]  {waffles}                => {chocolate}             0.005795628  0.1507937 0.038434164 3.039048    57
    ## [10] {chocolate}              => {waffles}               0.005795628  0.1168033 0.049618709 3.039048    57
    ## [11] {chicken}                => {frozen vegetables}     0.006710727  0.1563981 0.042907982 3.251956    66
    ## [12] {frozen vegetables}      => {chicken}               0.006710727  0.1395349 0.048093543 3.251956    66
    ## [13] {beef}                   => {root vegetables}       0.017386884  0.3313953 0.052465684 3.040367   171
    ## [14] {root vegetables}        => {beef}                  0.017386884  0.1595149 0.108998475 3.040367   171
    ## [15] {onions,                                                                                             
    ##       root vegetables}        => {other vegetables}      0.005693950  0.6021505 0.009456024 3.112008    56
    ## [16] {onions,                                                                                             
    ##       other vegetables}       => {root vegetables}       0.005693950  0.4000000 0.014234875 3.669776    56
    ## [17] {other vegetables,                                                                                   
    ##       root vegetables}        => {onions}                0.005693950  0.1201717 0.047381800 3.875044    56
    ## [18] {other vegetables,                                                                                   
    ##       yogurt}                 => {cream cheese}          0.005287239  0.1217799 0.043416370 3.071038    52
    ## [19] {chicken,                                                                                            
    ##       whole milk}             => {root vegetables}       0.005998983  0.3410405 0.017590239 3.128855    59
    ## [20] {frozen vegetables,                                                                                  
    ##       other vegetables}       => {root vegetables}       0.006100661  0.3428571 0.017793594 3.145522    60
    ## [21] {beef,                                                                                               
    ##       other vegetables}       => {root vegetables}       0.007930859  0.4020619 0.019725470 3.688692    78
    ## [22] {other vegetables,                                                                                   
    ##       root vegetables}        => {beef}                  0.007930859  0.1673820 0.047381800 3.190313    78
    ## [23] {beef,                                                                                               
    ##       whole milk}             => {root vegetables}       0.008032537  0.3779904 0.021250635 3.467851    79
    ## [24] {root vegetables,                                                                                    
    ##       whole milk}             => {beef}                  0.008032537  0.1642412 0.048906965 3.130449    79
    ## [25] {curd,                                                                                               
    ##       whole milk}             => {whipped/sour cream}    0.005897306  0.2256809 0.026131164 3.148329    58
    ## [26] {whipped/sour cream,                                                                                 
    ##       whole milk}             => {curd}                  0.005897306  0.1829653 0.032231825 3.434091    58
    ## [27] {curd,                                                                                               
    ##       tropical fruit}         => {yogurt}                0.005287239  0.5148515 0.010269446 3.690645    52
    ## [28] {tropical fruit,                                                                                     
    ##       yogurt}                 => {curd}                  0.005287239  0.1805556 0.029283172 3.388862    52
    ## [29] {whole milk,                                                                                         
    ##       yogurt}                 => {curd}                  0.010066090  0.1796733 0.056024403 3.372304    99
    ## [30] {margarine,                                                                                          
    ##       whole milk}             => {domestic eggs}         0.005185562  0.2142857 0.024199288 3.377404    51
    ## [31] {butter,                                                                                             
    ##       whole milk}             => {domestic eggs}         0.005998983  0.2177122 0.027554652 3.431409    59
    ## [32] {domestic eggs,                                                                                      
    ##       whole milk}             => {butter}                0.005998983  0.2000000 0.029994916 3.609174    59
    ## [33] {butter,                                                                                             
    ##       other vegetables}       => {whipped/sour cream}    0.005795628  0.2893401 0.020030503 4.036397    57
    ## [34] {other vegetables,                                                                                   
    ##       whipped/sour cream}     => {butter}                0.005795628  0.2007042 0.028876462 3.621883    57
    ## [35] {butter,                                                                                             
    ##       whole milk}             => {whipped/sour cream}    0.006710727  0.2435424 0.027554652 3.397503    66
    ## [36] {whipped/sour cream,                                                                                 
    ##       whole milk}             => {butter}                0.006710727  0.2082019 0.032231825 3.757185    66
    ## [37] {citrus fruit,                                                                                       
    ##       whole milk}             => {butter}                0.005083884  0.1666667 0.030503305 3.007645    50
    ## [38] {butter,                                                                                             
    ##       other vegetables}       => {root vegetables}       0.006609049  0.3299492 0.020030503 3.027100    65
    ## [39] {root vegetables,                                                                                    
    ##       whole milk}             => {butter}                0.008235892  0.1683992 0.048906965 3.038910    81
    ## [40] {whole milk,                                                                                         
    ##       yogurt}                 => {butter}                0.009354347  0.1669691 0.056024403 3.013104    92
    ## [41] {domestic eggs,                                                                                      
    ##       other vegetables}       => {whipped/sour cream}    0.005083884  0.2283105 0.022267412 3.185012    50
    ## [42] {domestic eggs,                                                                                      
    ##       other vegetables}       => {root vegetables}       0.007320793  0.3287671 0.022267412 3.016254    72
    ## [43] {pip fruit,                                                                                          
    ##       whipped/sour cream}     => {other vegetables}      0.005592272  0.6043956 0.009252669 3.123610    55
    ## [44] {tropical fruit,                                                                                     
    ##       whipped/sour cream}     => {yogurt}                0.006202339  0.4485294 0.013828165 3.215224    61
    ## [45] {other vegetables,                                                                                   
    ##       tropical fruit}         => {whipped/sour cream}    0.007829181  0.2181303 0.035892222 3.042995    77
    ## [46] {root vegetables,                                                                                    
    ##       yogurt}                 => {whipped/sour cream}    0.006405694  0.2480315 0.025826131 3.460127    63
    ## [47] {other vegetables,                                                                                   
    ##       yogurt}                 => {whipped/sour cream}    0.010167768  0.2341920 0.043416370 3.267062   100
    ## [48] {citrus fruit,                                                                                       
    ##       pip fruit}              => {tropical fruit}        0.005592272  0.4044118 0.013828165 3.854060    55
    ## [49] {pip fruit,                                                                                          
    ##       tropical fruit}         => {citrus fruit}          0.005592272  0.2736318 0.020437214 3.306105    55
    ## [50] {citrus fruit,                                                                                       
    ##       tropical fruit}         => {pip fruit}             0.005592272  0.2806122 0.019928826 3.709437    55
    ## [51] {pip fruit,                                                                                          
    ##       root vegetables}        => {tropical fruit}        0.005287239  0.3398693 0.015556685 3.238967    52
    ## [52] {root vegetables,                                                                                    
    ##       tropical fruit}         => {pip fruit}             0.005287239  0.2512077 0.021047280 3.320737    52
    ## [53] {pip fruit,                                                                                          
    ##       yogurt}                 => {tropical fruit}        0.006405694  0.3559322 0.017996950 3.392048    63
    ## [54] {other vegetables,                                                                                   
    ##       pip fruit}              => {tropical fruit}        0.009456024  0.3618677 0.026131164 3.448613    93
    ## [55] {other vegetables,                                                                                   
    ##       tropical fruit}         => {pip fruit}             0.009456024  0.2634561 0.035892222 3.482649    93
    ## [56] {citrus fruit,                                                                                       
    ##       root vegetables}        => {tropical fruit}        0.005693950  0.3218391 0.017691917 3.067139    56
    ## [57] {root vegetables,                                                                                    
    ##       tropical fruit}         => {citrus fruit}          0.005693950  0.2705314 0.021047280 3.268644    56
    ## [58] {other vegetables,                                                                                   
    ##       tropical fruit}         => {citrus fruit}          0.009049314  0.2521246 0.035892222 3.046248    89
    ## [59] {citrus fruit,                                                                                       
    ##       root vegetables}        => {other vegetables}      0.010371124  0.5862069 0.017691917 3.029608   102
    ## [60] {citrus fruit,                                                                                       
    ##       other vegetables}       => {root vegetables}       0.010371124  0.3591549 0.028876462 3.295045   102
    ## [61] {rolls/buns,                                                                                         
    ##       shopping bags}          => {sausage}               0.005998983  0.3072917 0.019522115 3.270794    59
    ## [62] {root vegetables,                                                                                    
    ##       yogurt}                 => {tropical fruit}        0.008134215  0.3149606 0.025826131 3.001587    80
    ## [63] {root vegetables,                                                                                    
    ##       tropical fruit}         => {other vegetables}      0.012302999  0.5845411 0.021047280 3.020999   121
    ## [64] {other vegetables,                                                                                   
    ##       tropical fruit}         => {root vegetables}       0.012302999  0.3427762 0.035892222 3.144780   121
    ## [65] {fruit/vegetable juice,                                                                              
    ##       other vegetables,                                                                                   
    ##       whole milk}             => {yogurt}                0.005083884  0.4854369 0.010472801 3.479790    50
    ## [66] {other vegetables,                                                                                   
    ##       whole milk,                                                                                         
    ##       yogurt}                 => {fruit/vegetable juice} 0.005083884  0.2283105 0.022267412 3.158135    50
    ## [67] {other vegetables,                                                                                   
    ##       whipped/sour cream,                                                                                 
    ##       whole milk}             => {root vegetables}       0.005185562  0.3541667 0.014641586 3.249281    51
    ## [68] {other vegetables,                                                                                   
    ##       root vegetables,                                                                                    
    ##       whole milk}             => {whipped/sour cream}    0.005185562  0.2236842 0.023182511 3.120474    51
    ## [69] {other vegetables,                                                                                   
    ##       whole milk,                                                                                         
    ##       yogurt}                 => {whipped/sour cream}    0.005592272  0.2511416 0.022267412 3.503514    55
    ## [70] {pip fruit,                                                                                          
    ##       root vegetables,                                                                                    
    ##       whole milk}             => {other vegetables}      0.005490595  0.6136364 0.008947636 3.171368    54
    ## [71] {other vegetables,                                                                                   
    ##       pip fruit,                                                                                          
    ##       whole milk}             => {root vegetables}       0.005490595  0.4060150 0.013523132 3.724961    54
    ## [72] {other vegetables,                                                                                   
    ##       root vegetables,                                                                                    
    ##       whole milk}             => {pip fruit}             0.005490595  0.2368421 0.023182511 3.130836    54
    ## [73] {other vegetables,                                                                                   
    ##       whole milk,                                                                                         
    ##       yogurt}                 => {pip fruit}             0.005083884  0.2283105 0.022267412 3.018056    50
    ## [74] {citrus fruit,                                                                                       
    ##       root vegetables,                                                                                    
    ##       whole milk}             => {other vegetables}      0.005795628  0.6333333 0.009150991 3.273165    57
    ## [75] {citrus fruit,                                                                                       
    ##       other vegetables,                                                                                   
    ##       whole milk}             => {root vegetables}       0.005795628  0.4453125 0.013014743 4.085493    57
    ## [76] {other vegetables,                                                                                   
    ##       root vegetables,                                                                                    
    ##       whole milk}             => {citrus fruit}          0.005795628  0.2500000 0.023182511 3.020577    57
    ## [77] {root vegetables,                                                                                    
    ##       tropical fruit,                                                                                     
    ##       whole milk}             => {yogurt}                0.005693950  0.4745763 0.011997966 3.401937    56
    ## [78] {tropical fruit,                                                                                     
    ##       whole milk,                                                                                         
    ##       yogurt}                 => {root vegetables}       0.005693950  0.3758389 0.015149975 3.448112    56
    ## [79] {root vegetables,                                                                                    
    ##       whole milk,                                                                                         
    ##       yogurt}                 => {tropical fruit}        0.005693950  0.3916084 0.014539908 3.732043    56
    ## [80] {root vegetables,                                                                                    
    ##       tropical fruit,                                                                                     
    ##       whole milk}             => {other vegetables}      0.007015760  0.5847458 0.011997966 3.022057    69
    ## [81] {other vegetables,                                                                                   
    ##       tropical fruit,                                                                                     
    ##       whole milk}             => {root vegetables}       0.007015760  0.4107143 0.017081851 3.768074    69
    ## [82] {other vegetables,                                                                                   
    ##       tropical fruit,                                                                                     
    ##       whole milk}             => {yogurt}                0.007625826  0.4464286 0.017081851 3.200164    75
    ## [83] {other vegetables,                                                                                   
    ##       whole milk,                                                                                         
    ##       yogurt}                 => {tropical fruit}        0.007625826  0.3424658 0.022267412 3.263712    75
    ## [84] {other vegetables,                                                                                   
    ##       whole milk,                                                                                         
    ##       yogurt}                 => {root vegetables}       0.007829181  0.3515982 0.022267412 3.225716    77
    ## [85] {other vegetables,                                                                                   
    ##       rolls/buns,                                                                                         
    ##       whole milk}             => {root vegetables}       0.006202339  0.3465909 0.017895272 3.179778    61

While deciding our threshold for lift, we kept in mind that while there
is no specific number of rules that is considered the “proper amount” as
it depends on the specific dataset and the goals of the analysis,
generating too many rules may lead to overfitting and reduced
interpretability, while generating too few rules may not capture all the
interesting patterns in the data. Since the ultimate goal is to identify
a set of high-quality rules that provide useful insights for the
specific problem at hand, we picked support = 0.005 and confidence = 0.1
in order to generate about 1.5k rules from over 9k shopping lists. This
allows us to then narrow down to 85 rules by restricting lift &gt; 3. We
believe that these 85 rules identity practical associations that can be
used to improve desired shopping metrics. Below are a few of the rules
that we found that made the most sense:

{whole milk, yogurt} =&gt; {butter}

{other vegetables, root vegetables} =&gt; {beef}

{ham} =&gt; {white bread}

{citrus fruit, pip fruit} =&gt; {tropical fruit}

{berries} =&gt; {whipped/sour cream}

These rules were all selected from the subset of 85 rules with lift &gt;
3. We see that items in the same list are often associated by type, such
as dairy or fruits, or by meals, such as vegetables and beef.
Interestingly, we noticed that despite nine out of the top ten rules in
terms of confidence resulted in the rhs of {whole milk}, none of the 85
rules with lift &gt; 3 had this result, although {whole milk} does
appear very frequently in the lhs.
